create database a_vs_f;
use a_vs_f;

-- 1. Orders Table Indexes
-- Indexing the IDs for joins, and platform/status since we filter by them constantly
ALTER TABLE orders ADD INDEX idx_order_id (order_id(255));
ALTER TABLE orders ADD INDEX idx_o_customer (customer_id(255));
ALTER TABLE orders ADD INDEX idx_platform_status (platform(50), order_status(50));

-- 2. Order Items Table Indexes
-- This table is heavily joined, so indexing both IDs is critical for performance
ALTER TABLE order_items ADD INDEX idx_oi_order (order_id(255));
ALTER TABLE order_items ADD INDEX idx_oi_product (product_id(255));

-- 3. Products Table Indexes
ALTER TABLE products ADD INDEX idx_product_id (product_id(255));
ALTER TABLE products ADD INDEX idx_p_category (category_id(255));

-- 4. Customers Table Indexes
ALTER TABLE customers ADD INDEX idx_customer_id (customer_id(255));

-- 5. Categories Table Indexes
ALTER TABLE categories ADD INDEX idx_category_id (category_id(255));

-- 6. Payments Table Indexes
ALTER TABLE payments ADD INDEX idx_pay_order (order_id(255));

-- 7. Reviews Table Indexes
ALTER TABLE reviews ADD INDEX idx_rev_product (product_id(255));
ALTER TABLE reviews ADD INDEX idx_rev_customer (customer_id(255));

-- Q1) Get a quick top-line comparison of total sales volume 
-- and revenue generated by Amazon versus Flipkart.

select platform,
count(order_id) AS Total_Orders, round(sum(total_amount), 2) AS Total_Revenue_INR
from orders
group by platform
order by Total_Revenue_INR desc;

-- Q2) Find out which metro city has the highest concentration of 
-- registered customers for each platform.

select platform, city, count(customer_id) AS Customer_Count
from customers
where city is not null and city != 'Unknown'
group by Platform, city
order by platform, Customer_Count desc;

-- Q3) Identify the most preferred payment methods across both 
-- platforms to understand consumer payment behavior.

select o.platform, p.payment_method, count(p.payment_id) as Transaction_Count
from payments p
join orders o on p.order_id = o.order_id
where p.payment_method is not null and p.payment_method != 'Unknown'
group by o.platform, p.payment_method
order by o.platform, Transaction_Count desc;

-- Q4) Identify products that have fewer than 50 units in stock on 
-- each platform to trigger inventory restocking.

SELECT platform, product_id,
product_name, stock_quantity
from products
where stock_quantity < 50
order by platform, stock_quantity asc;

-- Q5) Compare actual realized revenue and Average Order Value (AOV) 
-- strictly for successfully Delivered orders.

select platform, count(order_id) as Delivered_Orders,
round(sum(total_amount), 2) as Realized_Revenue_INR,
round(avg(total_amount), 2) as Average_Order_Value_INR
from orders
where order_status = 'Delivered'
group by platform;

-- Q6) Find the top 3 revenue-driving product categories for Amazon and Flipkart.

select platform, category_name, total_category_revenue
from (select o.platform, cat.category_name,
	  round(sum(oi.total_price), 2) as Total_Category_Revenue,
	  row_number() over (partition by o.platform order by sum(oi.total_price) desc) as category_rank
      from order_items oi
      join products p on oi.product_id = p.product_id
      join categories cat on p.category_id = cat.category_id
      join orders o on oi.order_id = o.order_id
      group by o.platform, cat.category_name
) ranked_categories
where category_rank <= 3;

-- Q7) For orders that were delayed beyond their promised ETA,
-- calculate the average number of days they were late.

select platform, count(order_id) as Delayed_Orders_Count,
round(avg(datediff(delivery_date, date_add(order_date, interval eta_days day))), 1) as Avg_Delay_In_Days
from orders
where order_status = 'Delivered'
  and date(delivery_date) > date(date_add(order_date, interval eta_days day))
group by platform;

-- Q8) Measure the potential revenue lost due to cancelled orders on each platform.

select platform,
sum(case when order_status = 'Cancelled' then 1 else 0 end) as Cancelled_Orders,
round(sum(case when order_status = 'Cancelled' then total_amount else 0 end), 2) as Lost_Revenue_INR,
round((SUM(case when order_status = 'Cancelled' then 1 else 0 end) * 100.0) / count(order_id), 2) as Cancellation_Rate_Pct
from orders
group by platform;

-- Q9) Evaluate product quality and customer satisfaction across categories 
-- by combining order reviews and catalog tables.

select p.platform, cat.category_name,
count(r.review_id) as Review_Count,
round(avg(r.rating), 2) as Avg_Star_Rating
from reviews r
join products p on r.product_id = p.product_id
join categories cat on p.category_id = cat.category_id
group by p.platform, cat.category_name
having Review_Count >= 10
order by Avg_Star_Rating desc;

-- Q10) Track monthly sales trajectory and growth rate across 
-- both platforms using window functions.

with MonthlySales as (
    select platform,
           date_format(order_date, '%Y-%m') as Sales_Month,
           round(sum(total_amount), 2) as Monthly_Revenue
    from orders
    where order_status != 'Cancelled'
    group by platform, date_format(order_date, '%Y-%m')
)
select platform, Sales_Month, Monthly_Revenue,
lag(Monthly_Revenue) over (partition by Platform order by Sales_Month) as Prev_Month_Revenue,
round(((Monthly_Revenue - lag(Monthly_Revenue) over (partition by Platform order by Sales_Month)) / 
lag(Monthly_Revenue) over (partition by Platform order by Sales_Month)) * 100, 2) 
as MoM_Growth_Percentage
from MonthlySales;

-- Q11) Identify high-value repeat buyers (customers who placed 2 or more orders) 
-- vs. single-time buyers per platform.

with CustomerOrderCounts as (
    select platform, customer_id,
           count(order_id) as Order_Count,
           sum(total_amount) as Customer_Lifetime_Spend
    from orders
    where order_status != 'Cancelled'
    group by platform, customer_id
)
select platform,
count(case when Order_Count = 1 then 1 end) as Single_Order_Customers,
count(case when Order_Count > 1 then 1 end) as Repeat_Customers,
round((count(case when Order_Count > 1 then 1 end) * 100.0 / count(customer_id)), 2) as Repeat_Customer_Percentage,
round(avg(Customer_Lifetime_Spend), 2) as Avg_Customer_LTV_INR
from CustomerOrderCounts
group by platform;

-- Q12) Quantify how delivery delays negatively impact star ratings by 
-- categorizing orders into "Early/On Time" vs. "Delayed".

with DeliveryPerformance as (
    select o.order_id, o.platform,
	case when date(o.delivery_date) > date(date_add(o.order_date, interval o.eta_days day)) then 'Delayed'
	else 'On Time / Early' end as Delivery_Status
    from orders o
    where o.order_status = 'Delivered'
)
select dp.platform, dp.Delivery_Status,
count(r.review_id) as Total_Reviews,
round(avg(r.rating), 2) as Avg_Rating
from DeliveryPerformance dp
join orders o on dp.order_id = o.order_id
join reviews r on o.customer_id = r.customer_id
group by dp.platform, dp.Delivery_Status;

-- Q13) Identify the vital few products on Amazon that generate 80% of 
-- its total revenue using cumulative running sums.

with AmazonDeliveredOrders as (
    select order_id 
    from orders 
    where platform = 'Amazon' and order_status = 'Delivered'
),
ProductRevenue as (
    select oi.product_id,
           round(sum(oi.total_price), 2) as Revenue
    from order_items oi
    join AmazonDeliveredOrders o on oi.order_id = o.order_id
    group by oi.product_id
),
CumulativeRevenue as (
    select product_id, Revenue,
        sum(Revenue) over (order by Revenue desc) as Running_Total,
        sum(Revenue) over () as Total_Amazon_Revenue
    from ProductRevenue
)
select cr.product_id, p.product_name, cr.Revenue,
    round((cr.Running_Total / cr.Total_Amazon_Revenue) * 100, 2) as Cumulative_Revenue_Percentage
from CumulativeRevenue cr
join products p on cr.product_id = p.product_id
where (cr.Running_Total / cr.Total_Amazon_Revenue) <= 0.80
order by cr.Revenue desc;

-- Q14) Find which product categories are most frequently purchased 
-- together within the exact same order line items.

with OrderCategories as (
    select distinct
	oi.order_id, cat.category_name
    from order_items oi
    join products p on oi.product_id = p.product_id
    join categories cat on p.category_id = cat.category_id
)
select oc1.category_name as Category_A,
       oc2.category_name as Category_B,
       count(oc1.order_id) as Co_Purchase_Count
from OrderCategories oc1
join OrderCategories oc2 
on oc1.order_id = oc2.order_id 
and oc1.category_name < oc2.category_name
group by Category_A, Category_B
order by Co_Purchase_Count desc
limit 10;